"""Generate the static multi-point coordinate artifact (ADR-012, #336).

Run ONCE, offline; the output (``assets/multipoint_coordinates.json``) is
committed and read at runtime by ``data.weather_client``. This keeps the
census download and matplotlib point-in-polygon in ``scripts/`` — the
production import path (``data/``, ``config.py``, ``jobs/``) stays
dependency-free.

The point selection is the study's, verbatim: ``select_points`` from
``scripts.multipoint_weather_study`` (census county centroids inside the
BA polygon → grid-snapped to the 0.25° ERA5 cell, populations summed →
top-K by population). The committed points are therefore exactly the
study's measured arm-B point set — which is the pre-flip validation
lever: re-running study arm B against this artifact must reproduce its
+1.11 sMAPE result.

**Weights are deliberately dropped.** The study measured the
population-weighted arm (C) against the unweighted arm (B) and found the
difference ~zero — the gain is spatial averaging, not load-weighting. So
production carries coordinates only, and needs no census data at runtime.

BAs whose footprint yields fewer than ``MULTIPOINT_MIN_CELLS`` cells (the
compact single-metro ones) are OMITTED — a missing key means the runtime
uses the single ``REGION_COORDINATES`` point, which is both correct and
the study's own fallback behavior.

Usage:
    python scripts/generate_multipoint_coords.py
    python scripts/generate_multipoint_coords.py --output assets/multipoint_coordinates.json
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from config import MULTIPOINT_K, REGION_COORDINATES  # noqa: E402
from scripts.multipoint_weather_study import (  # noqa: E402
    ERA5_CELL_DEG,
    load_census_counties,
    select_points,
)

DEFAULT_OUTPUT = Path(__file__).resolve().parents[1] / "assets" / "multipoint_coordinates.json"
SCHEMA_VERSION = 1


def build_coordinates() -> tuple[dict[str, list[list[float]]], list[str]]:
    """Returns ``({BA: [[lat, lon], ...]}, [single_point_BAs])``."""
    geojson = json.loads(
        (Path(__file__).resolve().parents[1] / "assets" / "ba_polygons.geojson").read_text()
    )
    counties = load_census_counties()

    coordinates: dict[str, list[list[float]]] = {}
    single: list[str] = []
    for ba in REGION_COORDINATES:
        pts = select_points(ba, geojson, counties)
        if bool(pts["is_single"].iloc[0]) and len(pts) == 1:
            single.append(ba)  # omit → runtime uses the single point
            continue
        coordinates[ba] = [
            [round(float(lat), 4), round(float(lon), 4)]
            for lat, lon in zip(pts["lat"], pts["lon"], strict=True)
        ]
    return coordinates, single


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    args = ap.parse_args()

    coordinates, single = build_coordinates()
    payload = {
        "schema": SCHEMA_VERSION,
        "cell_deg": ERA5_CELL_DEG,
        "k": MULTIPOINT_K,
        "note": (
            "Generated by scripts/generate_multipoint_coords.py (ADR-012). "
            "Coordinates only — the study measured population weighting as "
            "adding nothing. BAs absent here use their single "
            "config.REGION_COORDINATES point."
        ),
        "coordinates": dict(sorted(coordinates.items())),
    }
    args.output.write_text(json.dumps(payload, indent=2) + "\n")

    n_pts = sum(len(v) for v in coordinates.values())
    print(f"multi-point BAs: {len(coordinates)} ({n_pts} cells total)")
    for ba, pts in sorted(coordinates.items(), key=lambda kv: -len(kv[1]))[:8]:
        print(f"  {ba}: {len(pts)}")
    print(f"single-point (omitted): {len(single)} → {sorted(single)}")
    print(f"written → {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
